# Use postgres/example user/password credentials
version: '3.1'

services:
#Database
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

#Kafka
  kafka-zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:2
    ports:
      - 9092:9092
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - kafka-zookeeper

#Clickhouse
  clickhouse-server:
    image: yandex/clickhouse-server
    ports:
    - 8123:8123
    - 9000:9000
    - 9009:9009
    
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  clickhouse-client:
    image: yandex/clickhouse-client
    command: ['--host', 'server']  

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local


#Network
networks: 
  default: 
    external: 
      name: external-warehouse